---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.json$|\.ipynb$
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
        exclude: \.ipynb$
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: ^tests/test_data/|^tests/helpers\.py$
      - id: check-merge-conflict
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/jsh9/muff-pre-commit
    rev: 0.13.2
    hooks:
      - id: muff-format
        args: [--config, muff.toml]
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.18.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        args: [--wrap, '79', --number]
        additional_dependencies: [mdformat-gfm]
  - repo: https://github.com/jsh9/format-json
    rev: 0.1.2
    hooks:
      - id: format-json
        args:
          - --autofix
          - --no-ensure-ascii
          - --indent=4
          - --no-sort-keys
          - --no-eof-newline
  - repo: https://github.com/jsh9/markdown-toc-creator
    rev: 0.1.0
    hooks:
      - id: markdown-toc-creator
        exclude: ^tests/test_data/|^AGENTS\.md$|^CHANGELOG\.md$
  - repo: https://github.com/jsh9/markdown-heading-numbering
    rev: 0.1.0
    hooks:
      - id: markdown-heading-numbering
        exclude: ^CHANGELOG\.md$
  - repo: https://github.com/jsh9/format-docstring
    rev: 0.2.2
    hooks:
      - id: format-docstring
        name: Format docstrings in .py files
        args: [--line-length=79]
      - id: format-docstring-jupyter
        name: Format docstrings in .ipynb files
        args: [--line-length=79]
  - repo: local
    hooks:
      - id: check_full_diff_in_changelog
        name: Check "full diff" exists in CHANGELOG.md
        entry: python .pre_commit_helper_scripts/check_full_diff_in_changelog.py
        language: python
        additional_dependencies: [markdown-it-py]
